// https://github.com/antfu/eslint-config
import antfu from '@antfu/eslint-config'

export default antfu(
  {
    vue: true,
    typescript: true,
    ignores: [
      '**/__generated__/', // Ignore files generated by Tina
      '**/*-lock.json', // This will also catch Tina's lock file
      // ...globs
    ],
  },
  {
    files: ['**/*.vue'],
    rules: {
      'vue/operator-linebreak': ['error', 'before'],
      'vue/no-v-html': ['off'],
      'vue/multi-word-component-names': ['error'],
    },
  },
  {
    files: ['pages/**/*.vue'],
    rules: {
      'vue/multi-word-component-names': ['off'],
    },
  },
  {
    rules: {
      'node/prefer-global/process': 'off',
    },
  },
)
